name: Generate SBOM

on: [push]

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate CycloneDX SBOM
        uses: CycloneDX/gh-sbom-action@v1.1.0
        with:
          output-format: json
          output-file: bom.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: bom.json
